spring.application.name=school

spring.datasource.url= jdbc:postgresql://localhost:5432/hogwards
spring.datasource.username= student
spring.datasource.password= chocolatefrog
spring.jpa.hibernate.ddl-auto= validate
spring.jpa.show-sql=true
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
students.avatar.dir.path = avatars
